### ISSUE TITLE
Issue with abend analyzer

### ISSUE THREAD

**Issue by ssshreyas34** [BroadcomMFD/abend-analyzer-for-mainframe#5]
Hello Team,

Could you help me understand how to setup Abend Analyzer from Broadcomm. 
I am not completely aware what dataset is it expecting in the below screenshot. Anyways I have tried with multiple dataset but none of it worked. Suggest me where exactly i can get abend dataset from?

![unnamed](https://github.com/BroadcomMFD/abend-analyzer-for-mainframe/assets/64705522/1c193851-1c8f-4e0f-bc83-f511789d7e07)

Thanks,
Shreyas

**Comment by ssshreyas34** [comment]
Adding to it, How do we Acquire and install PTFs LU02175, LU03402, LU03403, and LU12023?

**Comment by zimlu02** [comment]
Hello Shreyas,

could we have an online meeting to better assist you with your issues? 

Thank you, 
Lukas

**Comment by ssshreyas34** [comment]
Thank you @zimlu02 for the response. The only problem I see meeting online is am with my company's laptop. Is it possible for you to send me your official working email address so i will be sending an email over it and will setup a call if it sounds ok to you?
Let me know the other process if it doesn't suits you.
Thanks,
Shreyas.

**Comment by zimlu02** [comment]
Sure! That is no problem.
Please contact me at:
lukas.zima@broadcom.com

Looking forward to meeting you.
